// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9LEBHw7fEhG2b54V7jLfqjuXuVCd_cTw',
    appId: '1:824040169201:web:2fc3b6c94a74f836b6d350',
    messagingSenderId: '824040169201',
    projectId: 'kurultai-32103',
    authDomain: 'kurultai-32103.firebaseapp.com',
    storageBucket: 'kurultai-32103.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6nI-cnMOmE4W0HMW_ohEtAQboRKBJS2M',
    appId: '1:824040169201:android:a3ca92ba712b807fb6d350',
    messagingSenderId: '824040169201',
    projectId: 'kurultai-32103',
    storageBucket: 'kurultai-32103.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiD0G-wEYalbaIkVvfWKqf35WK6GD6mXM',
    appId: '1:824040169201:ios:0ebe0a51692b9548b6d350',
    messagingSenderId: '824040169201',
    projectId: 'kurultai-32103',
    storageBucket: 'kurultai-32103.appspot.com',
    iosClientId: '824040169201-0luud4b732v0og7req566f74q8s9u52t.apps.googleusercontent.com',
    iosBundleId: 'com.example.cross',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiD0G-wEYalbaIkVvfWKqf35WK6GD6mXM',
    appId: '1:824040169201:ios:0ebe0a51692b9548b6d350',
    messagingSenderId: '824040169201',
    projectId: 'kurultai-32103',
    storageBucket: 'kurultai-32103.appspot.com',
    iosClientId: '824040169201-0luud4b732v0og7req566f74q8s9u52t.apps.googleusercontent.com',
    iosBundleId: 'com.example.cross',
  );
}
